version: '3.3'

services:
  db:
    restart: always
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres/backup:/backup
      - ./postgres/pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  web:
    restart: always
    image: reader
    container_name: reader
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - 8000:8000
      - 9000:9000
    build:
      context: ../
      dockerfile: _CI/Dockerfile
    command: ./docker-entrypoint.sh
    depends_on:
      - db
      - redis