# Generated by Django 3.1.7 on 2021-06-29 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountBd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название события')),
            ],
            options={
                'verbose_name': 'Название события',
                'verbose_name_plural': 'Список названий событий',
            },
        ),
        migrations.CreateModel(
            name='OrderOfDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_appeal', models.SmallIntegerField(verbose_name='Год призыва')),
                ('number_appeal', models.SmallIntegerField(choices=[(1, '1'), (2, '2')], verbose_name='Номер призыва')),
            ],
            options={
                'verbose_name': 'Очередь призыва в дежурствах',
                'verbose_name_plural': 'Очередь призыва в дежурствах',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата дежурсвта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расписание дежурств',
                'verbose_name_plural': 'Расписание дежурств',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_plan', models.DurationField(default=datetime.timedelta(0), verbose_name='Планируемое количество времени на событие')),
                ('respectful_absence', models.BooleanField(default=True, verbose_name='Уважительное событие')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к событию')),
                ('type_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='readerBd.listevents', verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата события')),
                ('type_of_day', models.CharField(choices=[('work', 'Рабочий день'), ('duty', 'Наряд'), ('hospital', 'Госпиталь'), ('business_trip', 'Командировка'), ('output', 'Выходной')], default='work', max_length=20, verbose_name='Тип дня')),
                ('plan_working_hours', models.DurationField(blank=True, default=datetime.timedelta(seconds=21600), null=True, verbose_name='Запланированное количество часов для работы')),
                ('real_working_hours', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Количество фактически отработанного времени')),
                ('time_of_respectful_absence_fact', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Время уважительного отсутствия ')),
                ('time_of_not_respectful_absence_fact', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Время не уважительных прогулов (фактическое)')),
                ('real_overtime', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Количество переработанного времени')),
                ('event', models.ManyToManyField(blank=True, related_name='days', to='readerBd.Event', verbose_name='Событие')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='days', to='accountBd.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='ControlTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Код')),
                ('time_entry', models.DateTimeField(verbose_name='Время входа')),
                ('time_exit', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('time_difference', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Время присутствия')),
                ('overtime', models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Время переработки')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_times', to='readerBd.day', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
    ]
