# Generated by Django 3.1.7 on 2021-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerBd', '0002_auto_20210616_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='respectful_absence',
            field=models.BooleanField(default=True, verbose_name='Уважительное событие'),
        ),
    ]
