# Generated by Django 3.1.7 on 2021-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerBd', '0003_auto_20210616_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderofduty',
            options={'verbose_name': 'Очередь призыва в дежурствах', 'verbose_name_plural': 'Очередь призыва в дежурствах'},
        ),
        migrations.AlterField(
            model_name='day',
            name='event',
            field=models.ManyToManyField(related_name='days', to='readerBd.Event', verbose_name='Событие'),
        ),
    ]
