# Generated by Django 3.1.7 on 2021-06-21 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerBd', '0005_auto_20210620_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_plan',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Планируемое количество времени на событие'),
        ),
    ]
